config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/report', to: "reports#index", as: "report"
  get '/links', to: "reports#all"
  get '/links/all', to: "reports#all", as: "all_digital_asset"
  get '/links/successful', to: "reports#successful", as: "successful_digital_asset"
  get '/links/errored', to: "reports#errored", as: "errored_digital_asset"
  get '/links/with-no-data', to: "reports#with_no_data", as: "digital_asset_with_no_data"
  get '/links/search', to: "reports#search", as: "digital_asset_search"

  post '/user/set_selected_dimensions', to: "static_pages#set_selected_dimensions", as: "set_selected_dimensions"

  resources :events

  resources :user_invites, only: [:create, :destroy]

  resources :digital_assets, only: [:new, :edit, :index, :create, :update, :destroy], path: 'digital_assets'

  resources :projects, only: [:new, :edit, :index, :create, :update, :destroy]


  devise_for :users,
             controllers: {omniauth_callbacks: 'users/omniauth_callbacks',
                              registrations: 'users/registrations'}
  namespace :admin do
    resources :users, only: [:index, :update, :new]
    resources :fellows, only: [:update, :index, :create, :destroy, :new]
    resources :ref_targets, only: [:index, :create, :update, :destroy, :new]
    resources :ref_impacts, only: [:index, :create, :update, :destroy, :new]
    resources :ref_partners, only: [:index, :create, :update, :destroy, :new]
  end

  resources :static_pages, only: [:index], path: 'home'
  root 'static_pages#home'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                 :integer          not null, primary key
#  description        :string
#  is_confidential    :boolean
#  event_date         :date
#  is_review_required :boolean
#  notes              :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  airtable_id        :string
#

class Event < ApplicationRecord
  #CONSTANTS
  #CUSTOM TABLES
  #GEMS
  #ASSOCIATIONS
  has_many :event_ref_impacts, dependent: :destroy
  has_many :ref_impacts, through: :event_ref_impacts

  has_many :event_projects, dependent: :destroy
  has_many :projects, through: :event_projects

  has_many :event_users, dependent: :destroy
  has_many :users, through: :event_users

  has_many :event_digital_assets, dependent: :destroy
  has_many :digital_assets, through: :event_digital_assets

  accepts_nested_attributes_for :event_digital_assets, allow_destroy: true, reject_if: :all_blank

  has_many :event_ref_countries, dependent: :destroy
  has_many :ref_countries, through: :event_ref_countries

  has_many :event_ref_partners, dependent: :destroy
  has_many :ref_partners, through: :event_ref_partners

  has_many :reports
  #ACCESSORS


  attr_accessor :event_ref_impacts_list
  attr_accessor :event_projects_list
  attr_accessor :event_users_list
  attr_accessor :event_digital_assets_list
  attr_accessor :event_ref_countries_list
  attr_accessor :event_ref_partners_list
  #VALIDATIONS
  #CALLBACKS
  after_create :add_event_ref_impacts,
               :add_event_projects,
               :add_event_users,
               :add_event_digital_assets,
               :add_event_ref_countries,
               :add_event_ref_partners

  after_update :update_event_ref_impacts,
               :update_event_projects,
               :update_event_users,
               :update_event_digital_assets,
               :update_event_ref_countries,
               :update_event_ref_partners

  #SCOPE
  #OTHER
  def add_event_ref_impacts
    event_ref_impacts_list.split(',').each do |a|
      EventRefImpact.create(event_id: self.id, ref_impact_id: a.to_i)      
    end
  end

  def add_event_projects
    event_projects_list.split(',').each do |a|
      EventProject.create(event_id: self.id, project_id: a.to_i)      
    end
  end

  def add_event_users
    event_users_list.split(',').each do |a|
      EventUser.create(event_id: self.id, user_id: a.to_i)      
    end
  end

  def add_event_digital_assets
    event_digital_assets_list.split(',').each do |a|
      EventDigitalAsset.create(event_id: self.id, digital_asset_id: a.to_i)      
    end
  end

  def add_event_ref_countries
    event_ref_countries_list.split(',').each do |a|
      EventRefCountry.create(event_id: self.id, ref_country_id: a.to_i)
    end
  end

  def add_event_ref_partners
    event_ref_partners_list.split(',').each do |a|
      EventRefPartner.create(event_id: self.id, ref_partner_id: a.to_i)
    end
  end


  def update_event_ref_impacts
    unless event_ref_impacts_list.nil?
      EventRefImpact.where(event_id: self.id).delete_all
      event_ref_impacts_list.split(',').each do |a|
        EventRefImpact.create(event_id: self.id, ref_impact_id: a.to_i)
      end
    end
  end

  def update_event_projects
    unless event_projects_list.nil?
      EventProject.where(event_id: self.id).delete_all
      event_projects_list.split(',').each do |a|
        EventProject.create(event_id: self.id, project_id: a.to_i)
      end
    end
  end

  def update_event_users
    unless event_users_list.nil?
      EventUser.where(event_id: self.id).delete_all
      event_users_list.split(',').each do |a|
        EventUser.create(event_id: self.id, user_id: a.to_i)
      end
    end
  end

  def update_event_digital_assets
    unless event_digital_assets_list.nil?
      EventDigitalAsset.where(event_id: self.id).delete_all
      event_digital_assets_list.split(',').each do |a|
        if a.to_i.to_s == a
          EventDigitalAsset.create(event_id: self.id, digital_asset_id: a.to_i)
        else
          if DigitalAsset.where(asset: a).first.present?
            EventDigitalAsset.create(event_id: self.id, digital_asset_id: DigitalAsset.where(asset: a).first.id)
          end
        end
      end
    end
  end

  def update_event_ref_countries
    unless event_ref_countries_list.nil?
      EventRefCountry.where(event_id: self.id).delete_all
      event_ref_countries_list.split(',').each do |a|
        EventRefCountry.create(event_id: self.id, ref_country_id: a.to_i)
      end
    end
  end

  def update_event_ref_partners
    unless event_ref_partners_list.nil?
      EventRefPartner.where(event_id: self.id).delete_all
      event_ref_partners_list.split(',').each do |a|
        EventRefPartner.create(event_id: self.id, ref_partner_id: a.to_i)
      end
    end
  end

  def short_description
    if self.description.present?
      if self.description.length > 200
        self.description[0..200].to_s + "..."
      else
        self.description.to_s
      end
    else
      "-"
    end
  end
#PRIVATE
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:update, :destroy, :show, :edit]

  def new
    @event = Event.new
    @event.event_digital_assets.build.build_digital_asset
    @ref_impacts = RefImpact.active
    @projects = Project.all
    @fellows = User.fellows.active
    # # For Digital Asset modal
    # @digital_asset = DigitalAsset.new
    @digital_assets = DigitalAsset.all
    @ref_countries = RefCountry.active
    @ref_partners = RefPartner.active
  end

  def edit
    @ref_impacts = RefImpact.active
    @projects = Project.all
    @fellows = User.fellows.active
    # # For Digital Asset modal
    @digital_asset = DigitalAsset.new
    @digital_assets = DigitalAsset.all
    @ref_countries = RefCountry.active
    @ref_partners = RefPartner.active
  end

  def index
    @events = Event.all.order("created_at DESC")
  end

  def show
  end

  def create
    @event = Event.new(event_params)
    build_event_digital_assets

    if @event.save
      redirect_to events_path, notice: "Event was created successfully"
    else
      redirect_to events_path, alert: "Something went wrong"
    end
  end

  def update
    # update_event_digital_assets
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { respond_with_bip(@event) }
      else
        format.html { redirect_to events_path, alert: "Something went wrong" }
        format.json { respond_with_bip(@event) }
      end
    end
  end

  def destroy
    if @event.destroy
      redirect_to events_path, notice: "Event was destroyed successfully"
    else
      redirect_to events_path, alert: "Something went wrong"
    end
  end

  def build_event_digital_assets
    @event.event_digital_assets.each do |eda|
      eda.digital_asset = DigitalAsset.create(
        asset: eda.digital_asset.asset,
        headline: eda.digital_asset.headline,
        publication: eda.digital_asset.publication,
        publish_date: eda.digital_asset.publish_date,
        post_type: eda.digital_asset.post_type,
      )
    end
  end

  # def update_event_digital_assets
  #   @event.event_digital_assets.each do |eda|
  #     asd
  #     a = DigitalAsset.find_or_initialize_by(id: eda.digital_asset.id)
  #     a.asset = eda.digital_asset.asset
  #     a.headline = eda.digital_asset.headline
  #     a.publication = eda.digital_asset.publication
  #     a.publish_date = eda.digital_asset.publish_date
  #     a.post_type = eda.digital_asset.post_type
  #     # a.save
  #   end
  # end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:description,
                                  :is_confidential,
                                  :event_date,
                                  :is_review_required,
                                  :notes,
                                  :event_ref_impacts_list,
                                  :event_projects_list,
                                  :event_users_list,
                                  :event_digital_assets_list,
                                  :event_ref_partners_list,
                                  :event_ref_countries_list,
                                  event_digital_assets_attributes:
                                    [:id,
                                     digital_asset_attributes: [
                                       :id,
                                       :asset,
                                       :headline,
                                       :publication,
                                       :publish_date,
                                       :post_type,
                                     ]
                                    ]
                                 )
  end
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.input :description, placeholder: "Event Description", input_html: {class: 'fellow-description-text'}, label: '<p class="fellow-lables">Description</p>'.html_safe, autofocus: true %>
  <div class="ui sixteen grid">
    <div class="eight wide column">
      <div class="ui checkbox">
        <%= f.input :is_confidential, as: :boolean, boolean_style: :inline, label: '<p class="fellow-lables">Is Confidential</p>'.html_safe %>
      </div>
    </div>
    <div class="eight wide column">
      <div class="ui checkbox">
        <%= f.input :is_review_required, as: :boolean, boolean_style: :inline, label: '<p class="fellow-lables">Is Review Required</p>'.html_safe %>
      </div><br /><br />
    </div>
  </div>
  <%= f.input :notes, placeholder: "Event Notes", label: '<p class="fellow-lables">Notes</p>'.html_safe %>

  <div class="ui calendar" id="event_date_calender">
    <div class="ui input left icon">
      <!-- <i class="calendar icon"></i> -->
      <%= f.input :event_date, as: :string, placeholder: "Event Date", label: '<p class="fellow-lables">Event Date</p>'.html_safe %>
    </div>
  </div>
  <br />

  <div class="field string">
    <label><p class="fellow-lables">Impacts</p></label>
    <div name="event_ref_impacts" class="ui search multiple selection dropdown" id="event_ref_impacts">
      <%= f.hidden_field :event_ref_impacts_list %>
      <div class="default text">Impacts</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <% @ref_impacts.each do |resource| %>
          <div class="item" data-value=<%= resource.id %>><%= resource.name %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="field string">
    <label><p class="fellow-lables">Projects</p></label>
    <div name="event_projects" class="ui search multiple selection dropdown" id="event_projects">
      <%= f.hidden_field :event_projects_list %>
      <div class="default text">Projects</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <% @projects.each do |resource| %>
          <div class="item" data-value=<%= resource.id %>><%= resource.name %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="field string">
    <label><p class="fellow-lables">Fellows</p></label>
    <div name="event_fellows" class="ui search multiple selection dropdown" id="event_fellows">
      <%= f.hidden_field :event_users_list %>
      <div class="default text">Fellows</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <% @fellows.each do |resource| %>
          <div class="item" data-value=<%= resource.id %>><%= resource.name %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="field string">
    <label><p class="fellow-lables">Countries</p></label>
    <div name="event_ref_countries" class="ui search multiple selection dropdown" id="event_ref_countries">
      <%= f.hidden_field :event_ref_countries_list %>
      <div class="default text">Countries</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <% @ref_countries.each do |resource| %>
          <div class="item" data-value=<%= resource.id %>><%= resource.name %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="field string">
    <label><p class="fellow-lables">Partners</p></label>
    <div name="event_ref_partners" class="ui search multiple selection dropdown" id="event_ref_partners">
      <%= f.hidden_field :event_ref_partners_list %>
      <div class="default text">Partners</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <% @ref_partners.each do |resource| %>
          <div class="item" data-value=<%= resource.id %>><%= resource.name %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="field string">
    <label><p class="fellow-lables">Digital Assets</p></label>
    <div name="event_digital_assets" class="ui search multiple selection dropdown" id="event_digital_assets">
      <%= f.hidden_field :event_digital_assets_list %>
      <div class="default text">Digital Assets</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <% @digital_assets.each do |resource| %>
          <div class="item" data-value=<%= resource.id %>><%= resource.asset %></div>
        <% end %>
      </div>
    </div>
  </div>

  <%= f.simple_fields_for :event_digital_assets do |builder| %>
    <%= render partial: "event_digital_assets/fields", locals: {f: builder} %>
    <%# This div is what makes the form get added. Dont play with it. %>
    <div id="links" style="display:none;">
      <%= link_to_add_association "Add Digital Asset", f, :event_digital_assets, partial: "event_digital_assets/fields" %>
    </div>
  <% end %>

  <%= f.button :submit %>
  <div class="ui basic button" id="cancelEventFormButton"><a>Cancel</a></div>
<% end %>



<script type="text/javascript">
 $(document).ready(function(){

   $('#event_ref_impacts')
     .dropdown('set selected', <%= @event.ref_impacts.pluck(:id).map{|a|a.to_s }.to_json.html_safe %>)
   ;
   $('#event_projects')
     .dropdown('set selected', <%= @event.projects.pluck(:id).map{|a|a.to_s }.to_json.html_safe %>)
   ;
   $('#event_fellows')
     .dropdown('set selected', <%= @event.users.fellows.pluck(:id).map{|a|a.to_s }.to_json.html_safe %>)
   ;
   $('#event_ref_countries')
     .dropdown('set selected', <%= @event.ref_countries.pluck(:id).map{|a|a.to_s }.to_json.html_safe %>)
   ;
   $('#event_ref_partners')
     .dropdown('set selected', <%= @event.ref_partners.pluck(:id).map{|a|a.to_s }.to_json.html_safe %>)
   ;
   $("#event_digital_assets")
     .dropdown('set selected', <%= @event.digital_assets.pluck(:id).map{|a|a.to_s }.to_json.html_safe %>)
   ;

   // Regexp for link
   a = /​^(https?:\/\/)(www\.)[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,4}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)|^(https?:\/\/)(www\.)?(?!ww)[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,4}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)/


   $('.remove_fields.dynamic').click();
   $('.remove_fields.existing').click();

   var asset_to_add;
   $("#event_digital_assets")
     .dropdown({
       allowAdditions: true,
       fullTextSearch: true,
       onAdd: function(addedValue, addedText, $addedChoice){
         if(addedValue === addedText){
           if (a.test(addedValue)){
             asset_to_add = addedValue;
             $('#links a').click();
           } else {
             alert("The added tag isnt a link. Please enter a link with http:// or https:// if not added");
             preventDefault();
           }
         }
       }
     })

   $('#new_event').on('cocoon:after-insert', function(event, element) {
     element.find('input[placeholder="Asset"]').val(asset_to_add);
   });
   $('.edit_event').on('cocoon:after-insert', function(event, element) {
     element.find('input[placeholder="Asset"]').val(asset_to_add);
   });

   $('#cancelEventFormButton').on('click', function(){
     alertify.confirm("Please Confirm", "Are you sure you want to continue. Your data will not be saved.", function(){

       window.location = "<%= events_path %>"
     }, function () {})
   });
 });
</script>

app/views/events/_new.html.erb
<div class="fellow-full-screen-modal">

  <div class="ui basic modal" id="newFormModal">
    <!-- <div class="ui red close actions button"> // addded "cancel"
         <i class="remove icon"></i>
         NE
         </div> -->
    <i class="close icon"></i>
    <div class="header">
      Add Event
    </div>
    <h2 class="ui sub header">
      <%= simple_form_for @event do |f| %>
        <%= f.input :description, input_html: {class: 'fellow-description-text'}, placeholder: "Event Description" %>
        <div class="ui checkbox"><%= f.input :is_confidential, as: :boolean, boolean_style: :inline %></div>&nbsp&nbsp&nbsp&nbsp
        <div class="ui checkbox"><%= f.input :is_review_required, as: :boolean, boolean_style: :inline%></div>
        <br><br><br>
        <%#= f.input :event_date, as: :string, placeholder: "Event Date" %>

        <div class="ui calendar" id="event_date_calender">
          <div class="ui input left icon">
            <!-- <i class="calendar icon"></i> -->
            <%= f.input :event_date, as: :string, placeholder:"Event Date" %>
          </div>
        </div>
        <br />

        <%= f.input :notes, as: :text, placeholder: "Event Notes" %>
        <div class="field string">
          <label>Impacts</label>
          <div name="event_ref_impacts" class="ui search multiple selection dropdown" id="event_ref_impacts">
            <%= f.hidden_field :event_ref_impacts %>
            <div class="default text">Impacts</div>
            <i class="dropdown icon"></i>
            <div class="menu">
              <% @ref_impacts.each do |resource| %>
                <div class="item" data-value=<%= resource.id %>><%= resource.name %></div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="field string">
          <label>Projects</label>
          <div name="event_projects" class="ui search multiple selection dropdown" id="event_projects">
            <%= f.hidden_field :event_projects %>
            <div class="default text">Projects</div>
            <i class="dropdown icon"></i>
            <div class="menu">
              <% @projects.each do |resource| %>
                <div class="item" data-value=<%= resource.id %>><%= resource.name %></div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="field string">
          <label>Fellows</label>
          <div name="event_fellows" class="ui search multiple selection dropdown" id="event_fellows">
            <%= f.hidden_field :event_users %>
            <div class="default text">Fellows</div>
            <i class="dropdown icon"></i>
            <div class="menu">
              <% @fellows.each do |resource| %>
                <div class="item" data-value=<%= resource.id %>><%= resource.name %></div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="field string">
          <label>Digital Assets</label>
          <div name="event_digital_assets" class="ui search multiple selection dropdown" id="event_digital_assets">
            <%= f.hidden_field :event_digital_assets %>
            <div class="default text">Digital Assets</div>
            <i class="dropdown icon"></i>
            <div class="menu">
              <% @digital_assets.each do |resource| %>
                <div class="item" data-value=<%= resource.id %>><%= resource.asset %></div>
              <% end %>
            </div>
          </div>
        </div>
        <br><br>

        <%= f.button :submit %>
      <% end %>
    </h2>

  </div>
</div>

<div class="ui modal" id="confirmationModal">

</div>


<script type="text/javascript">
 $(document).ready(function(){
   $('#event_ref_impacts')
     .dropdown()
   ;
   $('#event_projects')
     .dropdown()
   ;
   $('#event_users')
     .dropdown()
   ;

   $("#event_digital_assets")
     .dropdown({
       closable: false,
       allowAdditions: true,
       onNoResults: function(notFound){
         a = /​(https?:\/\/)?(www\.)[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,4}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)|(https?:\/\/)?(www\.)?(?!ww)[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,4}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)/
         if (a.test(notFound)) {

           $('#digital_asset_asset').val(notFound);
           $('#digital_asset_modal')
             .modal('show')
         }
       },
     })
   /* onAdd: function(addedValue, addedText, $addedChoice){
    *   if(addedValue === addedText){
    *     // Prefills the value for asset in the form
    *     $('#digital_asset_asset').val(addedValue);
    *     $('#digital_asset_modal')
    *       .modal({
    *         allowMultiple: true,
    *         closable: false,
    *         onHide: function(){
    *           var r = confirm("Are you sure you want to exit, your data will be lost.");
    *           if (r){
    *             return true
    *           } else {
    *             return false
    *           }}
    *       }).modal('show');
    *   }}
      })*/
 });


 $('#new_digital_asset').on('ajax:success', function(e, data, status, xhr){
   debugger;
   $('#digital_asset_modal')
     .modal('hide');
 }).on('ajax:error',function(e, xhr, status, error){
   
 });

</script>

app/views/events/edit.html.erb
<div class="ui three column centered grid fellow-top-padding">
  <div class="column">
    <h3><p>Edit Event</p></h3>
    <%= render partial: "form" %>
  </div>
</div>

app/views/events/index.html.erb
<div class="ui sixteen grid">
  <div class="sixteen wide column fellow-column-without-bottom-padding">
    <%= render partial: 'projects/projects' %>
  </div>

  <div class="sixteen wide column fellow-column-without-top-padding">
    <div style="overflow:auto;">
      <table class="ui celled selectable table">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th class="single line">Description</th>
            <th class="single line">Confidential</th>
            <th class="single line">Review Required</th>
            <th class="single line">Event Date</th>
            <th class="single line">Notes</th>
            <th class="single line">Impacts</th>
            <th class="single line">Projects</th>
            <th class="single line">Fellows</th>
            <th class="single line">Countries</th>
            <th class="single line">Partners</th>
            <th class="single line">Digital Assets</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |a| %>
            <tr>
              <td><%= link_to '<i class="trash icon"></i>'.html_safe, a, method: :delete, data: {confirm: "Are you sure?"}%></td>
              <td><%= link_to '<i class="edit icon"></i>'.html_safe, edit_event_path(a)%></td>
              <td><%= link_to a.description, event_path(a) %></td>
              <td>
                <center>
                  <%= best_in_place a, :is_confidential, as: :checkbox, collection: {false: '<i class="large remove icon"></i>'.html_safe, true: '<i class="large checkmark icon"></i>'.html_safe} %>
                </center>
                <%# if a.is_confidential %>
                <!-- <center>
                     <i class="large black checkmark icon"></i>
                     </center> -->
                <%# end %>
              </td>
              <td>
                <center>
                  <%= best_in_place a, :is_review_required, as: :checkbox, collection: {false: '<i class="large remove icon"></i>'.html_safe, true: '<i class="large checkmark icon"></i>'.html_safe} %>
                </center>
              </td>
              <td><%= a.event_date %></td>
              <td><%= a.notes %></td>
              <td>
                <% a.ref_impacts.each do |resource| %>
                  <div class="ui label"><%= resource.name %></div>
                <% end %>
              </td>
              <td>
                <% a.projects.each do |resource| %>
                  <div class="ui label"><%= resource.name %></div>
                <% end %>
              </td>
              <td>
                <% a.users.fellows.each do |resource| %>
                  <div class="ui label"><%= resource.name %></div>
                <% end %>
              </td>
              <td>
                <% a.ref_countries.each do |resource| %>
                  <div class="ui label"><%= resource.name %></div>
                <% end %>
              </td>
              <td>
                <% a.ref_partners.each do |resource| %>
                  <div class="ui label"><%= resource.name %></div>
                <% end %>
              </td>
              <td>
                <% a.digital_assets.each do |resource| %>
                  <div class="ui label"><%= link_to resource.asset, resource.asset, target: :_blank %></div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="ui three column centered grid fellow-top-padding">
  <div class="column">
    <h3><p>Add Event</p></h3>
    <%= render partial: "form" %>
  </div>
</div>

app/views/events/report_view.html.erb
<% if @event.reports.present? %>
  <div style="margin-top:20px; margin-bottom:20px;">
    <p class="fellow-lables">Metrics</p>
    <div>
      <% links = @event.reports.group_by{|a| a["asset"]} %>
      <% links.each do |link, metrics| %>
        <div style="margin-bottom:10px;">
          <div class="ui label"><%= link_to link, link, target: :_blank %></div><br>
          <% metric_genres = metrics.group_by{|a| a['genre']} %>
          <div class="ui sixteen grid">
            <% metric_genres.each do |genre, values| %>
              <div class="eight wide column">
                <table class="ui celled selectable table">
                  <thead>
                    <tr>
                      <th><%= genre.capitalize %></th>
                      <th><%= "Value" %></th>
                    </tr>
                  </thead>
                  <% values.each do |value| %>
                    <tr>
                      <td><%= value.metric_type.capitalize %></td>
                      <td><%= value.value %></td>
                    </tr>
                  <% end %>
                </table>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>



<% if @event.reports.present? %>
  <div style="margin-top:20px; margin-bottom:20px;">
    <p class="fellow-lables">Metrics</p>
    <div>
      <% links = @event.reports.group_by{|a| a["asset"]} %>
      <% links.each do |link, metrics| %>
        <div style="margin-bottom:10px;">
          <div class="ui label"><%= link_to link, link, target: :_blank %></div><br>
          <table class="ui celled selectable table">
            <thead>
              <tr>
                <th><%= "Metric Type" %></th>
                <th><%= "Value" %></th>
              </tr>
            </thead>
            <tbody>
              <% metrics.sort_by{|a| a["genre"]}.each do |metric| %>
                <tr>
                  <td><%= metric.genre.tr("_", " ").capitalize + " " + metric.metric_type.tr("_", " ") %></td>
                  <td><%= metric.value %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
<% end %>