config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/report', to: "reports#index", as: "report"
  get '/links', to: "reports#all"
  get '/links/all', to: "reports#all", as: "all_digital_asset"
  get '/links/successful', to: "reports#successful", as: "successful_digital_asset"
  get '/links/errored', to: "reports#errored", as: "errored_digital_asset"
  get '/links/with-no-data', to: "reports#with_no_data", as: "digital_asset_with_no_data"
  get '/links/search', to: "reports#search", as: "digital_asset_search"

  post '/user/set_selected_dimensions', to: "static_pages#set_selected_dimensions", as: "set_selected_dimensions"

  resources :events

  resources :user_invites, only: [:create, :destroy]

  resources :digital_assets, only: [:new, :edit, :index, :create, :update, :destroy], path: 'digital_assets'

  resources :projects, only: [:new, :edit, :index, :create, :update, :destroy]


  devise_for :users,
             controllers: {omniauth_callbacks: 'users/omniauth_callbacks',
                              registrations: 'users/registrations'}
  namespace :admin do
    resources :users, only: [:index, :update, :new]
    resources :fellows, only: [:update, :index, :create, :destroy, :new]
    resources :ref_targets, only: [:index, :create, :update, :destroy, :new]
    resources :ref_impacts, only: [:index, :create, :update, :destroy, :new]
    resources :ref_partners, only: [:index, :create, :update, :destroy, :new]
  end

  resources :static_pages, only: [:index], path: 'home'
  root 'static_pages#home'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  airtable_id :string
#

class Project < ApplicationRecord
  #CONSTANTS
  #CUSTOM TABLES
  #GEMS
  #ASSOCIATIONS
  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users

  has_many :project_ref_partners, dependent: :destroy
  has_many :ref_partners, through: :project_ref_partners

  has_many :event_projects, dependent: :destroy
  has_many :events, through: :event_projects

  #ACCESSORS
  attr_accessor :name_list
  attr_accessor :partner_list
  #VALIDATIONS
  validates :name, presence: true
  #CALLBACKS
  after_create :add_users
  after_create :add_partners
  after_update :update_users
  after_update :update_partners
  #SCOPE
  #OTHER
  def add_users
    # Gets a csv string from the controller
    name_list.split(',').each do |user|
      ProjectUser.create(project_id: self.id, user_id: user.to_i)
    end
  end

  def add_partners
    partner_list.split(',').each do |partner|
      ProjectRefPartner.create(project_id: self.id, ref_partner_id: partner.to_i)
    end
  end

  def update_users
    ProjectUser.where(project_id: self.id).delete_all
    name_list.split(',').each do |user|
      ProjectUser.create(project_id: self.id, user_id: user.to_i)
    end
  end

  def update_partners
    ProjectRefPartner.where(project_id: self.id).delete_all
    partner_list.split(',').each do |partner|
      ProjectRefPartner.create(project_id: self.id, ref_partner_id: partner.to_i)
    end
  end
#PRIVATE
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :update, :destroy, :edit]

  def index
    @projects = Project.all.order("created_at DESC")
  end

  def edit
    @users = User.fellows.active
    @partners = RefPartner.active
  end

  def new
    @project = Project.new
    @users = User.fellows.active
    @partners = RefPartner.active
  end

  def show
    @project_user = ProjectUser.new
    @project_partner = ProjectRefPartner.new
    @users = User.fellows.active.where.not(id: @project.users.pluck(:id))
    @partners = RefPartner.active.where.not(id: @project.ref_partners.pluck(:id))
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: "Project was created successfully"
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { respond_with_bip(@project) }
      else
        format.html { render :index }
        format.json { respond_with_bip(@project) }
      end
    end
  end

  def destroy
    @project.project_users.delete_all
    @project.project_ref_partners.delete_all
    if @project.destroy
      redirect_to projects_path, notice: "Project was destroyed successfully"
    else
      redirect_to projects_path, notice: "Something went wrong"
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :name_list, :partner_list)
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for([@project]) do |form| %>
  <%= form.input :name, input_html: {placeholder: "Project Name"}, autofocus: true %>

  <div class="field string">
    <label>Users</label>
    <div name="users" class="ui search multiple selection dropdown" id="name_list">
      <%= form.hidden_field :name_list %>
      <div class="default text">Project Users</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <% @users.each do |user| %>
          <div class="item" data-value=<%= user.id %>><%= user.name %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="field string">
    <label>Partners</label>
    <div name="partners" class="ui search multiple selection dropdown" id="partner_list">
      <%= form.hidden_field :partner_list %>
      <div class="default text">Project Partners</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <% @partners.each do |partner| %>
          <div class="item" data-value=<%= partner.id %>><%= partner.name %></div>
        <% end %>
      </div>
    </div><br />
  </div>
  <%= form.button :submit %>
  <div class="ui basic button" id="cancelEventFormButton"><a>Cancel</a></div>
<% end %>

app/views/projects/_projects.html.erb
<div class="ui tabular menu fellow-tabular-menu">
  <%= link_to "Report", report_path, class: "item #{controller_name == "reports" ? "active" : "fellow-tab"} " %>
  <%= link_to "Events", events_path, class: "item #{controller_name == "events" ? "active" : "fellow-tab"} " %>
  <%= link_to "Projects", projects_path, class: "item #{controller_name == "projects" ? "active" : "fellow-tab"} " %>
  <%= link_to "Digital Assets", digital_assets_path, class: "item #{controller_name == "digital_assets" ? "active" : "fellow-tab"} " %>
</div>

app/views/projects/_side.html.erb
<div class="ui secondary vertical pointing menu">
  <% if controller_name == "projects" %>
    <% @projects.each do |project| %>
      <%= link_to project.name.capitalize, project_path(project), class: "item #{project.id.to_s == params[:id] ? "active" : ""}" %>
    <% end %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<div class="ui three column centered grid fellow-top-padding">
  <div class="column">
    <h3><p>Add Project</p></h3>
    <%= render partial: "form" %>
  </div>
</div>

<script type="text/javascript">
 $('#name_list')
   .dropdown('set selected', <%= @project.users.pluck(:id).map{|a|a.to_s }.to_json.html_safe %>)
 ;
 $('#partner_list')
   .dropdown('set selected', <%= @project.ref_partners.pluck(:id).map{|a|a.to_s }.to_json.html_safe %>)
 ;

 $('#cancelEventFormButton').on('click', function(){
   alertify.confirm("Please Confirm", "Are you sure you want to continue. Your data will not be saved.", function(){
     window.location = "<%= projects_path %>"
   }, function () {})
 })


</script>

app/views/projects/index.html.erb
<div class="ui sixteen grid">
  <div class="sixteen wide column fellow-column-without-bottom-padding">
    <%= render partial: 'projects/projects' %>
  </div>
  <div class="sixteen wide column fellow-column-without-top-padding">
    <table class="ui celled selectable table">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th class="single line">Name</th>
          <th class="single line">Fellows</th>
          <th class="single line">Partners</th>
          <th class="single line">Created At</th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= link_to '<i class="trash icon"></i>'.html_safe, project, method: :delete, data: {confirm: "Are you sure?"}%></td>
            <td><%= link_to '<i class="edit icon"></i>'.html_safe, edit_project_path(project) %></td>
            <td><%= project.name %></td>

            <td>
              <% project.users.fellows.each do |resource| %>
                <div class="ui label"><%= resource.name %></div>
              <% end %>
            </td>
            <td>
              <% project.ref_partners.each do |resource| %>
                <div class="ui label"><%= resource.name %></div>
              <% end %>
            </td>
            <td><%= distance_of_time_in_words(project.created_at, Time.now) + " ago" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<div class="ui three column centered grid fellow-top-padding">
  <div class="column">
    <h3><p>Add Project</p></h3>
    <%= render partial: "form" %>
  </div>
</div>

<script type="text/javascript">
 $('#name_list')
   .dropdown()
 ;
 $('#partner_list')
   .dropdown()
 ;
 $('#cancelEventFormButton').on('click', function(){
   var data = $('#new_project').serializeArray().reduce(function(obj, item) {
     obj[item.name] = item.value;
     return obj;
   }, {});
   if (checkData(data)){
     alertify.confirm("Please Confirm", "Are you sure you want to continue. Your data will not be saved.", function(){

       window.location = "<%= projects_path %>"

     }, function () {})
   } else {
     window.location = "<%= projects_path %>"
   }
 });

 // Code to check if a form has any values filled
 function checkData(data) {
   var count = 0;
   for (variable in data)
 	 { if (!(variable === "utf8" || variable === "authenticity_token")) {
	   if (!(data[variable] == "")){
         return true;
       }
     }
     }
 };
</script>

app/views/projects/show.html.erb
<div style="width: 100%; margin-left: auto; margin-right: auto;">
  <div class="ui sixteen grid">
    <div class="sixteen wide column">
      <%= render partial: 'projects/projects' %>

        <div class="row" style="text-align:center">
          <%= link_to "Delete Project", @project, method: :delete, data: {confirm: "Are you sure"} %>
        </div><br />
        <div class="ui sixteen grid">
          <div class="eight wide column">
            <%= render partial: 'project_users/new', locals: {users: @users} %>
            <div class="ui message" style="text-align: center">
              <p><h3><%= pluralize(@project.users.count, "User") %> associated with <%= @project.name %></h3></p>
            </div>
            <table class="ui striped celled table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @project.users.each do |user| %>
                  <% project_user = ProjectUser.where(project_id: @project.id, user_id: user.id).first %>
                  <tr>
                    <td><%= user.name %></td>
                    <td><%= link_to "Delete", project_user, method: :delete, data: {confirm: "Are you sure"} %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          
          
          <div class="eight wide column">
            <%= render partial: 'project_ref_partners/new', locals: {partners: @partners} %>
            <div class="ui message" style="text-align: center">
              <p><h3><%= pluralize(@project.ref_partners.count, "Partner") %> associated with <%= @project.name %></h3></p>
            </div>
            <table class="ui striped celled table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @project.ref_partners.each do |partner| %>
                  <% project_partner = ProjectRefPartner.where(project_id: @project.id, ref_partner_id: partner.id).first %>
                  <tr>
                    <td><%= partner.name %></td>
                    <td><%= link_to "Delete", project_partner, method: :delete, data: {confirm: "Are you sure"} %></td>
                  </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      
    </div>
  </div>
</div>