config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/report', to: "reports#index", as: "report"
  get '/links', to: "reports#all"
  get '/links/all', to: "reports#all", as: "all_digital_asset"
  get '/links/successful', to: "reports#successful", as: "successful_digital_asset"
  get '/links/errored', to: "reports#errored", as: "errored_digital_asset"
  get '/links/with-no-data', to: "reports#with_no_data", as: "digital_asset_with_no_data"
  get '/links/search', to: "reports#search", as: "digital_asset_search"

  post '/user/set_selected_dimensions', to: "static_pages#set_selected_dimensions", as: "set_selected_dimensions"

  resources :events

  resources :user_invites, only: [:create, :destroy]

  resources :digital_assets, only: [:new, :edit, :index, :create, :update, :destroy], path: 'digital_assets'

  resources :projects, only: [:new, :edit, :index, :create, :update, :destroy]


  devise_for :users,
             controllers: {omniauth_callbacks: 'users/omniauth_callbacks',
                              registrations: 'users/registrations'}
  namespace :admin do
    resources :users, only: [:index, :update, :new]
    resources :fellows, only: [:update, :index, :create, :destroy, :new]
    resources :ref_targets, only: [:index, :create, :update, :destroy, :new]
    resources :ref_impacts, only: [:index, :create, :update, :destroy, :new]
    resources :ref_partners, only: [:index, :create, :update, :destroy, :new]
  end

  resources :static_pages, only: [:index], path: 'home'
  root 'static_pages#home'
end

app/models/report.rb
# == Schema Information
#
# Table name: event_report
#
#  event_id          :integer
#  event_name        :string
#  fellow            :string
#  impact_type       :string
#  impact_type_genre :string
#  ref_partner_id    :integer
#  partner_name      :string
#  project_id        :integer
#  project_name      :string
#  digital_asset_id  :integer
#  asset             :string
#  post_type         :string
#  metric_id         :integer
#  metric_type       :string
#  genre             :string
#  value             :integer
#

class Report < ApplicationRecord
  #CONSTANTS
  #CUSTOM TABLES
  self.table_name = "event_report"
  #GEMS
  #ASSOCIATIONS
  belongs_to :event
  #ACCESSORS
  #VALIDATIONS
  #CALLBACKS
  #SCOPE
  #OTHER
  class << self
    def refresh
      Report.connection.execute("REFRESH MATERIALIZED VIEW event_report;")
    end
  end
#PRIVATE
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_search_query, except: [:index]
  before_action :set_highlight, except: [:index]

  def index
    @report_data = Report.all.to_json
    @selected_dimensions = current_user.selected_dimensions
    @id = current_user.id
  end

  def all
    @links = DigitalAsset.order(custom_errors: :desc).page(params[:page]).per(20)
  end

  def successful
    @links = DigitalAsset.successful.page(params[:page]).per(20)
  end

  def errored
    @links = DigitalAsset.errored.order(custom_errors: :desc).page(params[:page]).per(20)
  end

  def with_no_data
    @links = DigitalAsset.with_no_data.order(custom_errors: :desc).where.not(tracked: false).page(params[:page]).per(20)
  end

  def search
    @search_text = params[:q]["asset_cont"]
    @links = @q.result.order(custom_errors: :desc).page(params[:page]).per(20)
  end

  private

    def set_search_query
      @q = DigitalAsset.ransack(params[:q])
    end

    def set_highlight
      @highlight = true
    end

end

app/views/reports/_header.html.erb
<div class="ui tabular menu fellow-tabular-menu">
  <%= link_to "All", all_digital_asset_path, class: "item #{action_name == "all" ? "active" : "fellow-tab"} " %>
  <%= link_to "Errored", errored_digital_asset_path, class: "item #{action_name == "errored" ? "active" : "fellow-tab"} " %>
  <%= link_to "Successful", successful_digital_asset_path, class: "item #{action_name == "successful" ? "active" : "fellow-tab"} " %>
  <%= link_to "With no Data", digital_asset_with_no_data_path, class: "item #{action_name == "with_no_data" ? "active" : "fellow-tab"} " %>


  <div class="right menu">
    <%= search_form_for q, url: digital_asset_search_path, html: { method: :get, class: "ui form" } do |f| %>
      <div class="item">
          <%= f.search_field :asset_cont, class: "ui input", placeholder: "Asset Contains", required: true %><br><br>
          <%= f.submit "Search", class: "ui blue basic button item" %>
          <% if action_name == 'search' %>
            <%= link_to "Reset", all_digital_asset_path, class: 'ui basic button item' %>
          <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/reports/_sidebar.html.erb
<div class="ui sixteen grid">
  <div class="four wide column fellow-top-padding">
    <%= search_form_for q, url: digital_asset_search_path, html: { method: :get, class: "ui form" } do |f| %>
      <h3>Search</h3>
      <%= f.search_field :asset_cont, class: "content-asset-search", placeholder: "Asset Contains", required: true %><br><br>
      <%= f.submit "Search", class: "ui button" %>
      <% if action_name == 'search' %>
        <%= link_to "Reset", all_digital_asset_path, class: 'clear-search' %>
      <% end %>
    <% end %>
  </div>

  <div class="twelve wide column fellow-top-padding">
    <div class="page-title" style="margin-left: 15px;">Show</div>
    <ul class="nav nav-pills nav-stacked">
      <li class="<%= action_name == 'all' ? 'active' : nil %>">
        <a href=<%= all_digital_asset_path %>> All</a>
      </li>
      <li class="<%= action_name == 'errored' ? 'active' : nil %>">
        <a href=<%= errored_digital_asset_path %>> Errored <span class="indication-dot indication-dot-red"></span></a>
      </li>
      <li class="<%= action_name == 'successful' ? 'active' : nil %>">
        <a href=<%= successful_digital_asset_path %>> Successful <span class="indication-dot indication-dot-green"></span></a>
      </li>
      <li class="<%= action_name == 'with_no_data' ? 'active' : nil %>">
        <a href=<%= digital_asset_with_no_data_path %>>With no data <span class="indication-dot indication-dot-grey"></span></a>
      </li>
    </ul>
  </div>
</div>

app/views/reports/_table.html.erb
<div class="sixteen wide column fellow-column-without-top-padding">
  <div style="overflow:auto;">
    <table class="ui celled selectable table">
      <thead>
        <tr>
          <th></th>
          <th class="single line">Asset</th>
          <th class="single line">Last tried</th>
          <th class="single line">Data freshness</th>
          <% if show_errors %>
            <th>Errors</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% links.each do |da| %>
          <tr>
            <td class="signal-area"><%= indicator(da.custom_errors, da.tracked).html_safe %></td>
            <td><a href="<%= da.asset %>" target="_blank"><%= da.asset %></a></td>
            <td>
              <% if da.last_requested_unixtime.present? %>
                <% time = Time.at(da.last_requested_unixtime) %>
                <%= distance_of_time_in_words(time, Time.now) + " ago" %>
              <% else %>
                <%= "Not requested" %>
              <% end %>
            </td>
            <td>
              <% if da.last_update_unixtime.present? %>
                <% time = Time.at(da.last_update_unixtime) %>
                <%= distance_of_time_in_words(time, Time.now) + " ago" %>
              <% else %>
                <%= "Not updated" %>
              <% end %>
            </td>
              <% if show_errors %>
                <td class="errors-column" title= "<%= da.custom_errors %>"><%= da.custom_errors %></td>
              <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate links %>
  </div>
</div>

app/views/reports/all.html.erb
<div class="sixteen wide column fellow-column-without-bottom-padding">
  <%= render "header", q: @q %>
</div>
  <%= render "table", links: @links, show_errors: false %>


<%= javascript_include_tag "jquery.timeago.js" %>

app/views/reports/errored.html.erb
<div class="sixteen wide column fellow-column-without-bottom-padding">
  <%= render "header", q: @q %>
</div>
<%= render "table", links: @links, show_errors: false %>

<%= javascript_include_tag "jquery.timeago.js" %>

app/views/reports/index.html.erb
<div class="sixteen wide column fellow-column-without-bottom-padding">
  <%= render partial: 'projects/projects' %>
</div>
<div style="border-bottom-width:2px;"></div>
<%= javascript_include_tag "react-pivot" %>
<div id="report_container"></div>

<script type="text/javascript">
 var rows = <%= @report_data.html_safe %>,
     selected_dimensions = "<%= @selected_dimensions %>",
     user_id = "<%= @id %>",
     react_pivot_options;

 selected_dimensions = selected_dimensions.split(",").filter(function(e) {return e !== ""})

 react_pivot_options = {
   rows: rows,
   dimensions: dimensions,
   calculations: calculations,
   reduce: reduce,
   tableClassName: "table table-striped",
   onDimensionChange: onDimensionChange
 };


 if (selected_dimensions && selected_dimensions.length > 0) {
   react_pivot_options.activeDimensions = selected_dimensions;
 }

 $(document).on('turbolinks:load', function() {
   ReactPivot(document.getElementById('report_container'), react_pivot_options);
 });


</script>

app/views/reports/search.html.erb
<div class="sixteen wide column fellow-column-without-bottom-padding">
  <%= render "header", q: @q %>
</div>
<%= render "table", links: @links, show_errors: true %>

<%= javascript_include_tag "jquery.timeago.js" %>

app/views/reports/successful.html.erb
<div class="sixteen wide column fellow-column-without-bottom-padding">
  <%= render "header", q: @q %>
</div>
<%= render "table", links: @links, show_errors: false %>

<%= javascript_include_tag "jquery.timeago.js" %>

app/views/reports/with_no_data.html.erb
<div class="sixteen wide column fellow-column-without-bottom-padding">
  <%= render "header", q: @q %>
</div>
<%= render "table", links: @links, show_errors: false %>

<%= javascript_include_tag "jquery.timeago.js" %>